INSERT INTO MODELO.CURSO
(NOMBRE)
VALUES( 'Front-end');

INSERT INTO MODELO.ALUMNO
(NOMBRE, CURSO_CURSO_ID)
VALUES( 'Hugo perez', 1);

INSERT INTO MODELO.ALUMNO
(NOMBRE, CURSO_CURSO_ID)
VALUES( 'Matias donoso', 1);

INSERT INTO MODELO.ALUMNO
(NOMBRE, CURSO_CURSO_ID)
VALUES( 'Matias molina', 1);

INSERT INTO MODELO.ALUMNO
(NOMBRE, CURSO_CURSO_ID)
VALUES( 'Edgardo pinto', 1);

INSERT INTO MODELO.ALUMNO
(NOMBRE, CURSO_CURSO_ID)
VALUES( 'luis pinto', 1);

INSERT INTO MODELO.ALUMNO
(NOMBRE, CURSO_CURSO_ID)
VALUES( 'juan jose', 1);

INSERT INTO MODELO.ALUMNO
(NOMBRE, CURSO_CURSO_ID)
VALUES( 'Ricardo maslo', 1);

INSERT INTO MODELO.ALUMNO
(NOMBRE, CURSO_CURSO_ID)
VALUES( 'Ricardo llo', 1);

INSERT INTO MODELO.ALUMNO
(NOMBRE, CURSO_CURSO_ID)
VALUES( 'Matias molina', 2);

INSERT INTO MODELO.ALUMNO
(NOMBRE, CURSO_CURSO_ID)
VALUES( 'Matias pinto', 2);

INSERT INTO MODELO.ALUMNO
(NOMBRE, CURSO_CURSO_ID)
VALUES( 'Edgardo don oso', 2);

INSERT INTO MODELO.UNIDAD
(NOMBRE)
VALUES('java');

INSERT INTO MODELO.TEST
(AUTOR, FECHA, UNIDAD_UNIDAD_ID)
VALUES('diego loazi', '02/03/2020', 1);

INSERT INTO MODELO.PREGUNTAS
(ENUNCIADO, PUNTAJE, TEST_TEST_ID)
VALUES('dos tres o cuatro', 10, 2);



INSERT INTO MODELO.PREGUNTAS
(ENUNCIADO, PUNTAJE, TEST_TEST_ID)
VALUES('1+1=2', 10, 2);

INSERT INTO MODELO.PREGUNTAS
(ENUNCIADO, PUNTAJE, TEST_TEST_ID)
VALUES('1+2=2', 10, 2);

ALTER TABLE ALTERNATIVAS ADD  correcta CHAR(1 byte)

INSERT INTO MODELO.ALTERNATIVAS
(DESCRIPCION, PORCENTAJE, PREGUNTAS_PREGUNTAS_ID,CORRECTA)
VALUES('si', 0,3,'f');

INSERT INTO MODELO.ALTERNATIVAS
(DESCRIPCION, PORCENTAJE, PREGUNTAS_PREGUNTAS_ID,CORRECTA)
VALUES('no', 0.3,3,'v');

INSERT INTO MODELO.ALTERNATIVAS
(DESCRIPCION, PORCENTAJE, PREGUNTAS_PREGUNTAS_ID,CORRECTA )
VALUES('tal vez', 0.3,3,'v');

INSERT INTO MODELO.ALTERNATIVAS
(DESCRIPCION, PORCENTAJE, PREGUNTAS_PREGUNTAS_ID,CORRECTA )
VALUES('cualquier otra', 0.4,3,'v');


INSERT INTO MODELO.PREGUNTAS
(ENUNCIADO, PUNTAJE, TEST_TEST_ID)
VALUES('1+2=2', 10, 2);


INSERT INTO MODELO.ALTERNATIVAS
(DESCRIPCION, PORCENTAJE, PREGUNTAS_PREGUNTAS_ID,CORRECTA)
VALUES('si', 0.4,4,'v');

INSERT INTO MODELO.ALTERNATIVAS
(DESCRIPCION, PORCENTAJE, PREGUNTAS_PREGUNTAS_ID,CORRECTA)
VALUES('no', 0.3,4,'v');

INSERT INTO MODELO.ALTERNATIVAS
(DESCRIPCION, PORCENTAJE, PREGUNTAS_PREGUNTAS_ID,CORRECTA )
VALUES('tal vez', 0.3,4,'v');

INSERT INTO MODELO.ALTERNATIVAS
(DESCRIPCION, PORCENTAJE, PREGUNTAS_PREGUNTAS_ID,CORRECTA )
VALUES('cualquier otra', 0,4,'f');

INSERT INTO MODELO.ALTERNATIVAS
(DESCRIPCION, PORCENTAJE, PREGUNTAS_PREGUNTAS_ID,CORRECTA)
VALUES('si', 1,5,'v');

INSERT INTO MODELO.ALTERNATIVAS
(DESCRIPCION, PORCENTAJE, PREGUNTAS_PREGUNTAS_ID,CORRECTA)
VALUES('no', 0,5,'f');

INSERT INTO MODELO.ALTERNATIVAS
(DESCRIPCION, PORCENTAJE, PREGUNTAS_PREGUNTAS_ID,CORRECTA )
VALUES('tal vez', 0,5,'f');

INSERT INTO MODELO.ALTERNATIVAS
(DESCRIPCION, PORCENTAJE, PREGUNTAS_PREGUNTAS_ID,CORRECTA )
VALUES('cualquier otra', 0,5,'f');

CREATE SEQUENCE evaluacion_s START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER EVALUACION BEFORE
    INSERT ON EVALUACION
    FOR EACH ROW
    WHEN ( new.EVALUACION_id IS NULL )
BEGIN
    :new.EVALUACION_id:= evaluacion_s.nextval;
END;

INSERT INTO MODELO.EVALUACION
( FECHA, ALUMNO_ALUMNO_ID)
VALUES( '02/02/202', 3);

CREATE SEQUENCE RESPUESTAS_s START WITH 1 NOCACHE ORDER;
CREATE OR REPLACE TRIGGER RESPUESTAS BEFORE
    INSERT ON RESPUESTAS
    FOR EACH ROW
    WHEN ( new.RESPUESTAS_id IS NULL )
BEGIN
    :new.RESPUESTAS_id:= RESPUESTAS_s.nextval;
END;

INSERT INTO MODELO.RESPUESTAS
(ALTERNATIVAS_ALTERNATIVAS_ID, EVALUACION_EVALUACION_ID)
VALUES( 5, 1);

INSERT INTO MODELO.RESPUESTAS
(ALTERNATIVAS_ALTERNATIVAS_ID, EVALUACION_EVALUACION_ID)
VALUES( 6, 1);

INSERT INTO MODELO.RESPUESTAS
(ALTERNATIVAS_ALTERNATIVAS_ID, EVALUACION_EVALUACION_ID)
VALUES( 14, 1);

INSERT INTO MODELO.RESPUESTAS
(ALTERNATIVAS_ALTERNATIVAS_ID, EVALUACION_EVALUACION_ID)
VALUES( 15, 1);

INSERT INTO MODELO.RESPUESTAS
(ALTERNATIVAS_ALTERNATIVAS_ID, EVALUACION_EVALUACION_ID)
VALUES( 9, 1);

INSERT INTO MODELO.RESPUESTAS
(ALTERNATIVAS_ALTERNATIVAS_ID, EVALUACION_EVALUACION_ID)
VALUES( 10, 1);








