

--pregunta 1--
SELECT c.NOMBRE,COUNT(e.EVALUACION_ID ) AS total_evaluciones
FROM CURSO c 
INNER JOIN ALUMNO a ON a.CURSO_CURSO_ID = c.CURSO_ID 
LEFT JOIN EVALUACION e ON e.ALUMNO_ALUMNO_ID = a.ALUMNO_ID 
GROUP BY c.NOMBRE 

--pregunta2--
SELECT c.NOMBRE,COUNT(e.EVALUACION_ID ) AS total_evaluciones
FROM CURSO c 
INNER JOIN ALUMNO a ON a.CURSO_CURSO_ID = c.CURSO_ID 
LEFT JOIN EVALUACION e ON e.ALUMNO_ALUMNO_ID = a.ALUMNO_ID
GROUP BY c.NOMBRE 
HAVING COUNT(e.EVALUACION_ID ) =0

--pregunta3--
SELECT TEST_ID ,count(PREGUNTAS_ID) 
FROM TEST t 
left JOIN PREGUNTAS p ON p.TEST_TEST_ID =t.TEST_ID
GROUP BY t.TEST_ID 
HAVING count(PREGUNTAS_ID)=0 

SELECT TEST_ID ,count(a.ALTERNATIVAS_ID) AS total_alternativas,p.PREGUNTAS_ID 
FROM TEST t 
LEFT JOIN PREGUNTAS p ON p.TEST_TEST_ID = t.TEST_ID
LEFT JOIN ALTERNATIVAS a ON a.PREGUNTAS_PREGUNTAS_ID = p.PREGUNTAS_ID 
GROUP BY p.PREGUNTAS_ID ,TEST_ID
HAVING count(a.ALTERNATIVAS_ID) <= 2

SELECT DISTINCT TEST_ID 
FROM TEST t 
LEFT JOIN PREGUNTAS p ON p.TEST_TEST_ID = t.TEST_ID
LEFT JOIN ALTERNATIVAS a ON a.PREGUNTAS_PREGUNTAS_ID = p.PREGUNTAS_ID 
WHERE  a.CORRECTA = 'f'
GROUP BY p.PREGUNTAS_ID ,TEST_ID,a.CORRECTA 
HAVING count(a.ALTERNATIVAS_ID) = 4 OR count(a.ALTERNATIVAS_ID) = 0

--pregunta 4 --
SELECT COUNT(CURSO_ID)
FROM CURSO 
INNER JOIN ALUMNO 
ON Alumno.CURSO_CURSO_ID = CURSO.CURSO_ID 

--pregunta 5 puntos totales de test 100--
SELECT sum(p.PUNTAJE*a.PORCENTAJE)- (((sum(p.PUNTAJE)-100)*-1)/4) AS puntaje_total
FROM EVALUACION e 
INNER JOIN RESPUESTAS r  ON r.EVALUACION_EVALUACION_ID =e.EVALUACION_ID 
INNER JOIN ALTERNATIVAS a ON a.ALTERNATIVAS_ID = r.ALTERNATIVAS_ALTERNATIVAS_ID 
INNER JOIN PREGUNTAS p ON a.PREGUNTAS_PREGUNTAS_ID = p.PREGUNTAS_ID 
WHERE a.CORRECTA = 'v'
GROUP BY e.EVALUACION_ID

--pregunta 6 puntaje normalizado--
SELECT ROUND((((sum(p.PUNTAJE*a.PORCENTAJE)- (((sum(p.PUNTAJE)-100)*-1)/4))*70)/100)) AS nota
FROM EVALUACION e 
INNER JOIN RESPUESTAS r  ON r.EVALUACION_EVALUACION_ID =e.EVALUACION_ID 
INNER JOIN ALTERNATIVAS a ON a.ALTERNATIVAS_ID = r.ALTERNATIVAS_ALTERNATIVAS_ID 
INNER JOIN PREGUNTAS p ON a.PREGUNTAS_PREGUNTAS_ID = p.PREGUNTAS_ID 
WHERE a.CORRECTA = 'v'
GROUP BY e.EVALUACION_ID

--pregunta 7--

SELECT al.ALUMNO_ID, al.NOMBRE ,c.NOMBRE 
FROM EVALUACION e 
INNER JOIN ALUMNO al ON al.ALUMNO_ID = e.ALUMNO_ALUMNO_ID 
INNER JOIN CURSO c ON c.CURSO_ID = al.CURSO_CURSO_ID 
INNER JOIN RESPUESTAS r  ON r.EVALUACION_EVALUACION_ID =e.EVALUACION_ID 
INNER JOIN ALTERNATIVAS a ON a.ALTERNATIVAS_ID = r.ALTERNATIVAS_ALTERNATIVAS_ID 
INNER JOIN PREGUNTAS p ON a.PREGUNTAS_PREGUNTAS_ID = p.PREGUNTAS_ID 
WHERE a.CORRECTA = 'v' AND EVALUACION_ID = 1
GROUP BY al.ALUMNO_ID,al.NOMBRE , c.NOMBRE 
HAVING ROUND((((sum(p.PUNTAJE*a.PORCENTAJE)- (((sum(p.PUNTAJE)-100)*-1)/4))*70)/100)) > 40

--pregunta 8--
SELECT AVG(ROUND((((sum(p.PUNTAJE*a.PORCENTAJE)- (((sum(p.PUNTAJE)-100)*-1)/4))*70)/100))) AS nota
FROM EVALUACION e 
INNER JOIN ALUMNO al ON al.ALUMNO_ID = e.ALUMNO_ALUMNO_ID 
INNER JOIN CURSO c ON c.CURSO_ID = al.CURSO_CURSO_ID 
INNER JOIN RESPUESTAS r  ON r.EVALUACION_EVALUACION_ID =e.EVALUACION_ID 
INNER JOIN ALTERNATIVAS a ON a.ALTERNATIVAS_ID = r.ALTERNATIVAS_ALTERNATIVAS_ID 
INNER JOIN PREGUNTAS p ON a.PREGUNTAS_PREGUNTAS_ID = p.PREGUNTAS_ID 
WHERE a.CORRECTA = 'v' AND EVALUACION_ID = 1
GROUP BY c.CURSO_ID 

